### ISSUE TITLE
IndexError: index 2373 is out of bounds for axis 0 with size 2373

### ISSUE THREAD

**Issue by mitrasafari** [gcamfer/gym-classification#1]
Hello,
first thanks for sharing your code.
I run your code with MNIST dataset without any problem but when I use it for my dataset after 13 epochs ,I get an error on 
 **# Update states for next step
self.true_labels = np.take(self.y,self.current_indices,axis=0).ravel()**
 and the erroe is:
IndexError: index 2373 is out of bounds for axis 0 with size 2373
do you know why this happend?

**Comment by mitrasafari** [comment]
I understand why this error happened, I write my solution in case someone has the same problem.
this error occurred because my length of x_train is 2373 and the code generate an index that includes 2373 
solution: 
in env_4_rl_classification.py file -> def step 
if(max(self.current_indices) + self.batch_size ) > len(self.X):
change to 
if(max(self.current_indices) + self.batch_size **+ 1**) > len(self.X):

**Comment by gcamfer** [comment]
Thanks for the bug fix, you could have opened a pull request
I'll change it rigth now.
